### PR TITLE
chore: add docker container

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
This adds docker container image and CI that builds and publishes it.

~Notable hacks in the Dockerfile:~

 - ~I had to download julia in advance in order to run some jula before make. I use the same command as in makefile. This should go~.
 - ~The `PATH` variable contains julia version, because julia is installed into a directory containing version number. This will make it hard to upgrade the version.~
 - ~I added instantiate and build calls.~
 - ~I also install Conda.jl and then ete3~

Work items:
 - [x] Pangraph crashes when running. Runtime dependencies, env vars etc need to be figured, so that the image can actually do something useful.
 - [x] Dev docs
 - [x] User docs

### CODE REVIEW

**Review by nnoll — APPROVED** [review]
This looks great. Tested commands on my end and everything works as expected.

**Comment by nnoll** [comment]
@ivan-aksamentov, do you want to verify that my last commit works on your end? It's an attempt to simplify the build

**Comment by ivan-aksamentov** [comment]
@nnoll I cleaned up some more and added a few things, notably running as non-root user:

```bash
docker run --rm -it \
--name "pangraph-$(date +%s)" \
--user="$(id -u):$(id -g)" \
--volume="$(pwd):/workdir" \
--workdir=/workdir \
neherlab/pangraph:latest \
bash -c "pangraph build --circular --alpha 0 --beta 0 /workdir/data/synthetic/test.fa | tee graph.json && pangraph polish graph.json | tee graph2.json"
```

This ensures that files written not as root, but as user `$(id -u):$(id -g)`, e.g. `1000:1000` on a single-user Ubuntu.

**Comment by ivan-aksamentov** [comment]
Overall the current thing works. I have nothing to add.

My impression is that Julia ecosystem is not ready for production quite yet. Science is great, but if you cannot ship it or if it's a pain to use, then it's not very useful. The 30 min single-threaded compilation is awful.

Regarding the PR, if there are no defects introduced to the usual dev and non-docker experience, then feel free to merge and make a release (see `docs/dev/releasing.md`). Don't forget to increment the version in Project.toml. There is already a mismatch between it and GitHub Releases. Perhaps worth adding this step to the dev docs.


The followup work may address the following:

 - Docker dev experience: the entire dockerfile is basically a single 30-min-long make target. This means that the docker build always runs almost fully, from scratch, and it takes 2 days to do even the simplest things with it.

   It would be nice to split the single `COPY` and single `RUN make` command into multiple `COPY` and `RUN` commands, to take advantage of docker layer caching.

   In particular, the filename-based targets, like `$(jc)` need to have hardcoded names, like `install-julia` so that they can be referred to conveniently from outside. And there should be a well-defined order of invocation of these targets.

 - Container size is almost 1 GB. The `/root/.julia/conda/3/lib` directory is about 800 Mb. Removing conda entirely would be great. But if not, pruning the libraries selectively, would be another way. For example, there is entire Qt 5 distribution there for some reason. There is an excellent tool to explore layers of a docker image: [dive](https://github.com/wagoodman/dive)

 - Research if there is a away to avoid the need for `/root/.julia/artifacts/` (e.g. whether they can be included in the `pagraph/` dir somehow).

**Comment by ivan-aksamentov** [comment]
CI seems to be working as expected: the new tag `0.5.0` is up and the `latest` tag points to it - both have the same digest.

https://hub.docker.com/r/neherlab/pangraph/tags

**Pull request merged**
